public static partial class MapGenerator {
    const string MapperBody = @"
        // O2 UNITY AUTO ASSET MAPPER
        // ==============================
        // Auto Generated Mapper Script
        //
        // WARNING:
        // - This file is automatically generated. Do NOT modify manually unless you know what you are doing.
        // Purpose:
        // This class provides mapping between keys and addressable assets for UI {1}.
        //
        // ==============================

        using UnityEngine.AddressableAssets;
        using UnityEngine.ResourceManagement.AsyncOperations;

        public class {0}Mapper : BaseMapper<{1}, {0}AssetKey> {{
            public override string KeyScript => ""{0}.Keys.g"";
            [UnityEngine.Scripting.Preserve]
            public static {0}Mapper Instance {{
                get {{
                    if (instance)
                        return instance;

                    AsyncOperationHandle<{0}Mapper> handle =
                        Addressables.LoadAssetAsync<{0}Mapper>(
                            ""{2}"");
                    handle.WaitForCompletion();
                    instance = handle.Result;
                    return instance;
                }}
            }}

            static {0}Mapper instance;
        }}
    ";

    static string GetMapperSource(string mapName, string assetTypeName, string label) {
        return string.Format(MapperBody, mapName, assetTypeName, label);
    }
}