using UnityEditor;
using UnityEngine;

[CustomEditor(typeof(AutoGeneratedScriptable), true)]
public class AutoGeneratedScriptableEditor : Editor {
    public override void OnInspectorGUI() {
        DrawDefaultInspector();

        AutoGeneratedScriptable scriptable = (AutoGeneratedScriptable)target;

        if (string.IsNullOrEmpty(scriptable.KeyScript))
            return;

        GUILayout.Space(10);
        if (GUILayout.Button($"Edit Keys"))
            OpenScriptByName(scriptable.KeyScript);
    }

    static void OpenScriptByName(string scriptName) {
        var guids = AssetDatabase.FindAssets($"t:MonoScript {scriptName}");
        foreach (var guid in guids) {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            MonoScript script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
            if (script == null || script.name != scriptName)
                continue;
            AssetDatabase.OpenAsset(script);
            return;
        }
    }
}