
        // O2 UNITY AUTO ASSET MAPPER
        // ==============================
        // Auto Generated Mapper Script
        //
        // WARNING:
        // - This file is automatically generated. Do NOT modify manually unless you know what you are doing.
        // Purpose:
        // This class provides mapping between keys and addressable assets for UI UnityEngine.AudioClip.
        //
        // ==============================

        using UnityEngine.AddressableAssets;
        using UnityEngine.ResourceManagement.AsyncOperations;

        public class VfxSoundMapper : BaseMapper<UnityEngine.AudioClip, VfxSoundAssetKey> {
            public override string KeyScript => "VfxSound.Keys.g";
            [UnityEngine.Scripting.Preserve]
            public static VfxSoundMapper Instance {
                get {
                    if (instance)
                        return instance;

                    AsyncOperationHandle<VfxSoundMapper> handle =
                        Addressables.LoadAssetAsync<VfxSoundMapper>(
                            "Mapper_VfxSound");
                    handle.WaitForCompletion();
                    instance = handle.Result;
                    return instance;
                }
            }

            static VfxSoundMapper instance;
        }
    